### ISSUE TITLE
world stone bug

### ISSUE THREAD

**Issue by lostopkk** [intergrav/Adrenaline#9] opened 2022-12-13 00:21 UTC
I went to play the alpha version of 1.19.3 and every time I open a world I'm on the stone map, I don't know why I opened about 10 worlds and they all only have stone

**Comment by intergrav** [comment] 2022-12-13 01:37
Can't reproduce. Are you on Fabric or Quilt? Also, try disabling C2ME and Fastload and see if it works again

**Comment by intergrav** [comment] 2022-12-13 05:05
Interesting, I've never seen this before lol. I'm not sure how I could fix this, maybe there is a config somewhere causing the issue? I can't reproduce as I said before so I really don't know what the issue is

I'm using GraalVM, Prism Launcher and 1.19.3 Quilt

**Comment by intergrav** [comment] 2022-12-13 05:06
nevermind, I think I can actually. Is this what it looks like?

![image](https://user-images.githubusercontent.com/42325132/207231428-8239a74d-b19a-401a-96fe-5d6641b20573.png)

**Comment by intergrav** [comment] 2022-12-13 05:11
Yup it's definitely C2ME. Weirdly enough, it only happens to me on Quilt, but works perfectly fine on Fabric. I'll look into this when I have time (and temporarily remove C2ME from the next alpha update if it's still broken by then)

**Comment by lostopkk** [comment] 2022-12-13 12:40
> nevermind, I think I can actually. Is this what it looks like?
> 
> ![image](https://user-images.githubusercontent.com/42325132/207231428-8239a74d-b19a-401a-96fe-5d6641b20573.png)
> 

yes, it's very weird

**Comment by lostopkk** [comment] 2022-12-13 18:32
https://github.com/RelativityMC/C2ME-fabric/issues/186#issuecomment-1349333626

@intergrav I opened the issue on c2me's github and they sent me a build that seems to have fixed the problem, you'll probably have to use it to maintain version 1.19.3 while the fix hasn't been added yet.

**Comment by intergrav** [comment] 2022-12-13 21:54
Yup it’s been uploaded now, https://modrinth.com/mod/c2me-fabric/version/0.2.0+alpha.9.12+1.19.3

I’ll update when I can

**Comment by intergrav** [comment] 2022-12-15 02:55
Should be fixed in the latest release.

**Closed by intergrav** 2022-12-15 02:55 UTC
